sudo: false
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "skip test"
deploy:
  skip_cleanup: true
  provider: pypi
  user: "__token__"
  password:
    secure: O6otZKQpQFZS3Kck8ciF6lxqzzvR4X/ZXjf2NSSAbfw2OD6AZR3WsLQ7wSyEpFKBbtw7zYLbePO977p6H+XnIyIwNBd8yhJKLFqCWWTBNp8c6bQly3Xf6y4/VnQuHCtJM5arn27qQZzXV9FkuZvWPHsvLPu6JR+/4Tqjz8bSymyV6aU6ATDnZLJYa1XUND0qU2/gmgbSrzonuwxMUcPNgKBHCuiqy9/cP/J8jjrYzc4vurluk1gQ/bvEcCZtCoK0K/PP0xxU1fifvP2034KHBeQ75LLMYPh8RInuj1RWDrWe2kasaYi/196tQB1kilsk4Aon08PY1FV7AFuKqepUxdUs/b3XkrQyPQ/t1SekCwXcmdzTNHBdwgBW+bBK5cyYIEFn9CzjaHDHeF4NY+nNNz0f1HQ2wHam+QUTnkbtZDV/KngXm3Jx4Hc2l3qFaXMP2ngqeexm6J6IoYDa+uPSQdMXRbp3QIb/cGnlinrS4kdOaVhEJuSshaWN/B7ojoM8Ani3iDr4wzj/7h3155piJ2OsBODS/3V238ZV/qAQykM2Gbi9PCmAt2VM0GcqaWlBF5I9urRaNDBoZpsG911xNscOikobwGkDvkbCoJSrkZ7w/gPrKaLtCB3zBOp1zyWTUDx0QhZbtj6FaL+zB6dNEIi3eD3WCWUU8Fj8N74rrfg=
  on:
    tags: true
